<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from remoteeventformeditor/xml/schema/CRM/RemoteEventFormEditor/RemoteEventFormEditorForm.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:1ce9cfb60c8593f0848b0a608422acc4)
 */
use CRM_RemoteEventFormEditor_ExtensionUtil as E;

/**
 * Database access object for the RemoteEventFormEditorForm entity.
 */
class CRM_RemoteEventFormEditor_DAO_RemoteEventFormEditorForm extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_remote_event_form_editor_form';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique RemoteEventFormEditorForm ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Name of the form
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $name;

  /**
   * Fields in the form
   *
   * @var string
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $fields;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_remote_event_form_editor_form';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Remote Event Form Editor Forms') : E::ts('Remote Event Form Editor Form');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique RemoteEventFormEditorForm ID'),
          'required' => TRUE,
          'where' => 'civicrm_remote_event_form_editor_form.id',
          'table_name' => 'civicrm_remote_event_form_editor_form',
          'entity' => 'RemoteEventFormEditorForm',
          'bao' => 'CRM_RemoteEventFormEditor_DAO_RemoteEventFormEditorForm',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Name'),
          'description' => E::ts('Name of the form'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_remote_event_form_editor_form.name',
          'table_name' => 'civicrm_remote_event_form_editor_form',
          'entity' => 'RemoteEventFormEditorForm',
          'bao' => 'CRM_RemoteEventFormEditor_DAO_RemoteEventFormEditorForm',
          'localizable' => 0,
          'add' => NULL,
        ],
        'fields' => [
          'name' => 'fields',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Fields'),
          'description' => E::ts('Fields in the form'),
          'required' => TRUE,
          'where' => 'civicrm_remote_event_form_editor_form.fields',
          'table_name' => 'civicrm_remote_event_form_editor_form',
          'entity' => 'RemoteEventFormEditorForm',
          'bao' => 'CRM_RemoteEventFormEditor_DAO_RemoteEventFormEditorForm',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'remote_event_form_editor_form', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'remote_event_form_editor_form', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
