-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_remote_event_form_editor_form`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_remote_event_form_editor_form
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_remote_event_form_editor_form` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique RemoteEventFormEditorForm ID',
  `name` varchar(255) NOT NULL COMMENT 'Name of the form',
  `fields` text NOT NULL COMMENT 'Fields in the form',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
